# Project Name
TARGET = TranceGate

# Sources
CPP_SOURCES = TranceGate.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy/
DAISYSP_DIR = ../../daisysp/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
